### ISSUE TITLE
Include `graph_out` + `schema.sql` to the Subtivity Substreams

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subtivity-substreams#12]
Include `graph_out` + `schema.sql` to the Subtivity Substreams

## Scope

- [x] include `graph_out` map module
- [x] include `schema.sql` to support Clickhouse Sink
- [x] Drop extras (no longer required)

We could DROP the:
- Grafana
- Prometheus
- KV
- `store_daw`
- `sink`

Since our Graph out + Clickhouse Sink, would most likely be able to solve all that

The `schema.sql` is pretty straight forward

```yaml
transaction_traces: number
trace_calls: number
uaw: number[]
```
